const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Behaviors.Physics,
		C3.Plugins.video,
		C3.Plugins.Text,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Physics.Exps.AngularVelocity,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.video.Cnds.HasEnded
	];
};
self.C3_JsPropNameTable = [
	{anaysayfa_btn: 0},
	{basla_btn: 0},
	{bilgi_btn: 0},
	{ses_ac_btn: 0},
	{tam_ekran_btn: 0},
	{yeniden_oyna_btn: 0},
	{yeniden_oyna_btn1: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{giris: 0},
	{bilgi: 0},
	{Mouse: 0},
	{arka_plan: 0},
	{Keyboard: 0},
	{Browser: 0},
	{yonerge: 0},
	{tebrikler: 0},
	{Audio: 0},
	{Touch: 0},
	{sopa_uzun: 0},
	{Physics: 0},
	{sopa_kisa: 0},
	{zemin: 0},
	{el: 0},
	{el_sopa: 0},
	{madalya: 0},
	{kayip: 0},
	{yonerge1: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Video: 0},
	{Text: 0},
	{Sprite: 0},
	{arkaplan: 0},
	{Sprite4: 0},
	{PlatformInfo: 0},
	{Fam_butonlar: 0},
	{Ilk_X: 0},
	{Ilk_Y: 0},
	{Gecis_Hiz_X: 0},
	{Gecis_Hiz_Y: 0},
	{Gecis_Acisal_Hiz: 0},
	{Gecis_Y_Konumu: 0},
	{Vurus_Durumu: 0},
	{MuzikSesi: 0},
	{AnlikSes: 0},
	{Ses_Kapali: 0},
	{LayoutMuzikSesi: 0},
	{Ilk_X2: 0},
	{Ilk_Y2: 0},
	{Gecis_Hiz_X2: 0},
	{Gecis_Hiz_Y2: 0},
	{Gecis_Acisal_Hiz2: 0},
	{Gecis_Y_Konumu2: 0},
	{Oyun_Bitti: 0},
	{isLoader: 0}
];

self.InstanceType = {
	anaysayfa_btn: class extends self.ISpriteInstance {},
	basla_btn: class extends self.ISpriteInstance {},
	bilgi_btn: class extends self.ISpriteInstance {},
	ses_ac_btn: class extends self.ISpriteInstance {},
	tam_ekran_btn: class extends self.ISpriteInstance {},
	yeniden_oyna_btn: class extends self.ISpriteInstance {},
	yeniden_oyna_btn1: class extends self.ISpriteInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	giris: class extends self.ISpriteInstance {},
	bilgi: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	arka_plan: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	yonerge: class extends self.ISpriteInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	sopa_uzun: class extends self.ISpriteInstance {},
	sopa_kisa: class extends self.ISpriteInstance {},
	zemin: class extends self.ISpriteInstance {},
	el: class extends self.ISpriteInstance {},
	el_sopa: class extends self.ISpriteInstance {},
	madalya: class extends self.ISpriteInstance {},
	kayip: class extends self.ISpriteInstance {},
	yonerge1: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Text: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Fam_butonlar: class extends self.ISpriteInstance {}
}